import webPush from 'web-push';

type VercelRequest = {
  method?: string;
  body?: unknown;
  query?: Record<string, string | string[]>;
};

type VercelResponse = {
  status: (code: number) => VercelResponse;
  json: (payload: unknown) => void;
};

// Valid VAPID keys generated by the user
const VAPID_PUBLIC_KEY = process.env.VITE_VAPID_PUBLIC_KEY || 'BEjz8oIUeEp29dUbSKWjNFvo0Rtt1hWCi0SvFSBVePNFamrVbIb_CarvRxLY5Av0wnURkaNtoArFeBRPs0XMfnc';
const VAPID_PRIVATE_KEY = process.env.VAPID_PRIVATE_KEY || 'cZlQNs3i82J-1wdm31J1X6ASe0yCc1mx5b3UOkfwx38';
const FIREBASE_DB_URL = 'https://dairy-farm-app-b95a9-default-rtdb.firebaseio.com';

webPush.setVapidDetails(
  'mailto:omwengakevin@gmail.com',
  VAPID_PUBLIC_KEY,
  VAPID_PRIVATE_KEY
);

export default async function handler(req: VercelRequest, res: VercelResponse) {
  try {
    // 1. Fetch the data from Firebase Realtime Database
    const dbRes = await fetch(`${FIREBASE_DB_URL}/.json`);
    if (!dbRes.ok) {
      return res.status(500).json({ error: 'Failed to fetch database' });
    }
    
    const dbData = await dbRes.json();
    
    // We assume default_farm_001 since the user's app uses it for offline sync
    const farmData = dbData['farmData']?.['default_farm_001'];
    const subscriptions = dbData['pushSubscriptions'] || {};
    
    if (!farmData) {
      return res.status(200).json({ message: 'No farm data found.' });
    }
    
    const todos = farmData.jr_farm_todos || [];
    const cows = farmData.jr_farm_cows || [];
    const bsfs = farmData.jr_farm_bsfs || [];
    const vets = farmData.jr_farm_vets || [];
    const quarantine = farmData.jr_farm_quarantine || [];
    const sprays = farmData.jr_farm_sprays || [];
    const inventory = farmData.jr_farm_inventory || [];
    const aiRecords = farmData.jr_farm_ai || [];
    const staffOff = farmData.jr_farm_staff_off || [];
    const azolla = farmData.jr_farm_azolla || [];
    
    const notificationsToSend: { text: string; daysLeft: number }[] = [];
    const today = new Date().toISOString().split('T')[0];
    const now = Date.now();
    const msPerDay = 1000 * 3600 * 24;

    const diffDays = (targetDate: string) => Math.ceil((new Date(targetDate).getTime() - now) / msPerDay);
    
    // Evaluate Employee Leaves
    staffOff.forEach((leave: any) => {
      if (leave.status === 'Approved') {
        const startDays = diffDays(leave.startDate);
        const endDays = diffDays(leave.endDate);
        
        // Reminder for leave starting
        if (startDays <= 3 && startDays >= 0) {
          notificationsToSend.push({ 
            text: `👤 Staff Alert: ${leave.staffName} begins ${leave.type} in ${startDays} days.`, 
            daysLeft: startDays 
          });
        }
        
        // Reminder for staff returning
        if (endDays === 0) {
          notificationsToSend.push({ 
            text: `👤 Staff Returning: ${leave.staffName} finishes leave today!`, 
            daysLeft: 0 
          });
        }
      }
    });

    // Evaluate Todos
    let todoCount = 0;
    todos.forEach((todo: any) => {
      if (!todo.completed && todo.date === today) {
        todoCount++;
      }
    });
    if (todoCount > 0) notificationsToSend.push({ text: `📋 ${todoCount} Task(s) due today.`, daysLeft: 0 });
    
    // Evaluate Cows (Dry-off)
    cows.forEach((cow: any) => {
      if (cow.pregnancyStatus === 'pregnant' && cow.dueDate) {
        const days = diffDays(cow.dueDate);
        if (days <= 7 && days >= 0) {
          notificationsToSend.push({ text: `🐄 Cow ${cow.name || cow.id} due to calve in ${days} days (Dry-off alert).`, daysLeft: days });
        }
      }
    });

    // Evaluate Vet Records
    vets.forEach((vet: any) => {
      if (vet.nextDueDate) {
        const days = diffDays(vet.nextDueDate);
        if (days <= 3 && days >= 0) {
          notificationsToSend.push({ text: `💉 ${vet.animalCategory || 'Animal'} ${vet.cowId} due for ${vet.type} in ${days} days.`, daysLeft: days });
        }
      }
    });

    // Evaluate Quarantine
    quarantine.forEach((q: any) => {
      if (q.dateScheduledEnd && q.quarantineStatus !== 'Cleared & Released' && q.quarantineStatus !== 'Failed & Culled') {
        const days = diffDays(q.dateScheduledEnd);
        if (days <= 1 && days >= 0) {
          notificationsToSend.push({ text: `🚧 ${q.animalTagOrBatch} finishes quarantine in ${days} days.`, daysLeft: days });
        }
      }
    });

    // Evaluate Sprays (Chemicals)
    sprays.forEach((spray: any) => {
      if (spray.safeDate && spray.safeDate === today) {
        notificationsToSend.push({ text: `🌿 Block ${spray.block} is safe to harvest today (PHI over).`, daysLeft: 0 });
      }
      if (spray.nextSprayDate) {
        const days = diffDays(spray.nextSprayDate);
        if (days <= 1 && days >= 0) {
          notificationsToSend.push({ text: `🐛 Block ${spray.block} due for ${spray.chemical} spray in ${days} days.`, daysLeft: days });
        }
      }
    });

    // Evaluate Inventory
    inventory.forEach((item: any) => {
      if (item.quantity <= item.minStock) {
        notificationsToSend.push({ text: `📦 Low Stock: ${item.name} (${item.quantity} ${item.unit} left).`, daysLeft: 0 });
      }
      if (item.expiryDate) {
        const days = diffDays(item.expiryDate);
        if (days <= 14 && days >= 0) {
          notificationsToSend.push({ text: `⚠️ ${item.name} expires in ${days} days!`, daysLeft: days });
        }
      }
    });

    // Evaluate AI Records
    aiRecords.forEach((ai: any) => {
      if (ai.status === 'Pending') {
        if (ai.returnHeatDate && diffDays(ai.returnHeatDate) === 0) {
          notificationsToSend.push({ text: `🔥 Cow ${ai.cowId}: Check for return heat today (21 days post-AI).`, daysLeft: 0 });
        }
        if (ai.checkDate && diffDays(ai.checkDate) === 0) {
          notificationsToSend.push({ text: `🩺 Cow ${ai.cowId}: Due for pregnancy check today.`, daysLeft: 0 });
        }
      }
    });

    // Evaluate BSF
    bsfs.forEach((bsf: any) => {
      if (bsf.status !== 'Harvested') {
        const start = new Date(bsf.startDate || bsf.inoculationDate).getTime();
        const d = Math.floor((now - start) / msPerDay);
        if (d === 14) {
          notificationsToSend.push({ text: `🪰 BSF Batch ${bsf.batchId || bsf.id} ready for final larvae harvest!`, daysLeft: 0 });
        } else if (d > 0 && d % 3 === 0) {
          // Remind every 3 days for feeding and egg harvesting
          notificationsToSend.push({ text: `🐛 BSF Batch ${bsf.batchId || bsf.id}: Add feed substrate and harvest eggs from love cages today.`, daysLeft: 0 });
        }
      }
    });

    // Evaluate Azolla Ponds (Water & Nutrients)
    if (azolla.length > 0) {
      const sortedAzolla = [...azolla].sort((a: any, b: any) => b.date.localeCompare(a.date));
      const latest = sortedAzolla[0];
      const d = Math.ceil((now - new Date(latest.date).getTime()) / msPerDay);
      if (d >= 3) {
        notificationsToSend.push({ text: `💧 Azolla Ponds: Last harvest was ${d} days ago. Top up water levels and add manure/nutrients!`, daysLeft: 0 });
      }
    }

    if (notificationsToSend.length === 0) {
      return res.status(200).json({ message: 'No alarms triggered.' });
    }

    // Send the notifications
    const subKeys = Object.keys(subscriptions);
    if (subKeys.length === 0) {
      return res.status(200).json({ message: 'Alarms triggered, but no active push subscriptions found.' });
    }

    let sentCount = 0;
    const errors: any[] = [];
    
    // Sort by upcoming (daysLeft ascending) and map back to strings
    notificationsToSend.sort((a, b) => a.daysLeft - b.daysLeft);
    const sortedAlerts = notificationsToSend.map(n => n.text);

    // Bundle all alerts into a single payload, no truncation
    const title = sortedAlerts.length === 1 ? "JR Farm Alert" : `JR Farm: ${sortedAlerts.length} Alerts`;
    const body = sortedAlerts.join('\n');

    const payload = JSON.stringify({ title, body });

    for (const key of subKeys) {
      const sub = subscriptions[key];
      try {
        await webPush.sendNotification(sub, payload);
        sentCount++;
      } catch (err: any) {
        if (err.statusCode === 410 || err.statusCode === 404) {
          // Subscription expired or invalid, delete it from Firebase
          await fetch(`${FIREBASE_DB_URL}/pushSubscriptions/${key}.json`, { method: 'DELETE' });
        } else {
          errors.push(err.message);
        }
      }
    }

    res.status(200).json({ 
      message: `Sent ${sentCount} bundled notifications out of ${subKeys.length} subscriptions.`,
      alerts: notificationsToSend,
      errors
    });
    
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
}
