import type { VercelRequest, VercelResponse } from '@vercel/node';
import webPush from 'web-push';

// Valid VAPID keys generated by the user
const VAPID_PUBLIC_KEY = process.env.VITE_VAPID_PUBLIC_KEY || 'BEjz8oIUeEp29dUbSKWjNFvo0Rtt1hWCi0SvFSBVePNFamrVbIb_CarvRxLY5Av0wnURkaNtoArFeBRPs0XMfnc';
const VAPID_PRIVATE_KEY = process.env.VAPID_PRIVATE_KEY || 'cZlQNs3i82J-1wdm31J1X6ASe0yCc1mx5b3UOkfwx38';
const FIREBASE_DB_URL = 'https://dairy-farm-app-b95a9-default-rtdb.firebaseio.com';

webPush.setVapidDetails(
  'mailto:omwengakevin@gmail.com',
  VAPID_PUBLIC_KEY,
  VAPID_PRIVATE_KEY
);

export default async function handler(req: VercelRequest, res: VercelResponse) {
  try {
    // 1. Fetch the data from Firebase Realtime Database
    const dbRes = await fetch(`${FIREBASE_DB_URL}/.json`);
    if (!dbRes.ok) {
      return res.status(500).json({ error: 'Failed to fetch database' });
    }
    
    const dbData = await dbRes.json();
    
    // We assume default_farm_001 since the user's app uses it for offline sync
    const farmData = dbData['farmData']?.['default_farm_001'];
    const subscriptions = dbData['pushSubscriptions'] || {};
    
    if (!farmData) {
      return res.status(200).json({ message: 'No farm data found.' });
    }
    
    const todos = farmData.jr_farm_todos || [];
    const cows = farmData.jr_farm_cows || [];
    const bsfs = farmData.jr_farm_bsfs || [];
    
    const notificationsToSend: { title: string, body: string }[] = [];
    
    // Evaluate Todos
    const today = new Date().toISOString().split('T')[0];
    todos.forEach((todo: any) => {
      if (!todo.completed && todo.date === today) {
        notificationsToSend.push({
          title: "Task Due Today!",
          body: `Don't forget: ${todo.text}`
        });
      }
    });
    
    // Evaluate Cows (Breeding/PD/Deworming logic replicated)
    cows.forEach((cow: any) => {
      if (cow.pregnancyStatus === 'pregnant' && cow.dueDate) {
        const dueTime = new Date(cow.dueDate).getTime();
        const diffDays = Math.ceil((dueTime - Date.now()) / (1000 * 3600 * 24));
        if (diffDays <= 7 && diffDays >= 0) {
          notificationsToSend.push({
            title: "Drying Off Alert",
            body: `${cow.name || cow.id} is due to calve in ${diffDays} days! Ensure dry-off.`
          });
        }
      }
    });

    // Evaluate BSF
    bsfs.forEach((bsf: any) => {
      const start = new Date(bsf.startDate).getTime();
      const diffDays = Math.floor((Date.now() - start) / (1000 * 3600 * 24));
      if (diffDays === 14) {
        notificationsToSend.push({
          title: "BSF Harvest Alert",
          body: `Batch ${bsf.id} (Pupae phase) is ready for harvesting!`
        });
      }
    });

    if (notificationsToSend.length === 0) {
      return res.status(200).json({ message: 'No alarms triggered.' });
    }

    // Send the notifications
    const subKeys = Object.keys(subscriptions);
    if (subKeys.length === 0) {
      return res.status(200).json({ message: 'Alarms triggered, but no active push subscriptions found.' });
    }

    let sentCount = 0;
    const errors: any[] = [];
    
    // For simplicity, just send the first/most critical alarm so we don't spam them.
    const primaryAlert = notificationsToSend[0];
    const payload = JSON.stringify(primaryAlert);

    for (const key of subKeys) {
      const sub = subscriptions[key];
      try {
        await webPush.sendNotification(sub, payload);
        sentCount++;
      } catch (err: any) {
        if (err.statusCode === 410 || err.statusCode === 404) {
          // Subscription expired or invalid, delete it from Firebase
          await fetch(`${FIREBASE_DB_URL}/pushSubscriptions/${key}.json`, { method: 'DELETE' });
        } else {
          errors.push(err.message);
        }
      }
    }

    res.status(200).json({ 
      message: `Sent ${sentCount} notifications out of ${subKeys.length} subscriptions.`,
      alert: primaryAlert,
      errors
    });
    
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
}
